name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-slim
    steps:

      - name: Checkout branch
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6

      - name: Install workloads
        run: dotnet workload restore src/ScratchcardStatistics/ScratchcardStatistics.csproj

      - name: Publish Blazor project
        run: |
          dotnet publish src/ScratchcardStatistics/ScratchcardStatistics.csproj \
            --output release \
            --property RestoreLockedMode=true \
            --property Version=$(git rev-list --count HEAD)

      - name: Change base tag in index.html from '/' to '/ScratchcardStatistics/'
        run: sed -i 's/<base href="\/" \/>/<base href="\/ScratchcardStatistics\/" \/>/g' release/wwwroot/index.html

      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Add .gitattributes file
        run: echo "* binary" > release/wwwroot/.gitattributes

      - name: Commit files to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
